on: push
name: Pipeline
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: nuxt/actions-yarn@master
      with:
        args: install --ignore-scripts
    - name: Lint
      uses: nuxt/actions-yarn@master
      with:
        args: lint
    - name: Test
      uses: nuxt/actions-yarn@master
      with:
        args: test
    - name: Journey test
      uses: cypress-io/github-action@v1
      env:
        PORT: 3000
        GOOGLE_CLIENT_ID: test
        GOOGLE_CLIENT_SECRET: test
        GOOGLE_CALLBACK_URL: http://localhost:3000/auth/google/callback
        BASE_URL: http://localhost:3000
        TARGET_URI: postgres://postgres:example@localhost/postgres
      with:
        start: yarn dev
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - name: Database migrations
      if: github.ref == 'refs/heads/master'
      uses: ./db
      env:
        TARGET_URI: ${{ secrets.TARGET_URI }}
    - name: Deploy to PCF
      if: github.ref == 'refs/heads/master'
      uses: d3sandoval/cloud-foundry-action@1.1.1
      env:
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_TARGET_ORG: dsandoval-org
        CF_TARGET_SPACE: development
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
      with:
        args: push tome -b https://github.com/cloudfoundry/nodejs-buildpack
